generic_hw_control_loop:
  loop_hz: 100
  cycle_time_error_threshold: 0.03

# Settings for ros_control hardware interface
hardware_interface:
  sim_control_mode: 0
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
