// Generated by gencpp from file ur_dashboard_msgs/GetRobotModeResponse.msg
// DO NOT EDIT!


#ifndef UR_DASHBOARD_MSGS_MESSAGE_GETROBOTMODERESPONSE_H
#define UR_DASHBOARD_MSGS_MESSAGE_GETROBOTMODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ur_dashboard_msgs/RobotMode.h>

namespace ur_dashboard_msgs
{
template <class ContainerAllocator>
struct GetRobotModeResponse_
{
  typedef GetRobotModeResponse_<ContainerAllocator> Type;

  GetRobotModeResponse_()
    : robot_mode()
    , answer()
    , success(false)  {
    }
  GetRobotModeResponse_(const ContainerAllocator& _alloc)
    : robot_mode(_alloc)
    , answer(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef  ::ur_dashboard_msgs::RobotMode_<ContainerAllocator>  _robot_mode_type;
  _robot_mode_type robot_mode;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _answer_type;
  _answer_type answer;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetRobotModeResponse_

typedef ::ur_dashboard_msgs::GetRobotModeResponse_<std::allocator<void> > GetRobotModeResponse;

typedef boost::shared_ptr< ::ur_dashboard_msgs::GetRobotModeResponse > GetRobotModeResponsePtr;
typedef boost::shared_ptr< ::ur_dashboard_msgs::GetRobotModeResponse const> GetRobotModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator1> & lhs, const ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.robot_mode == rhs.robot_mode &&
    lhs.answer == rhs.answer &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator1> & lhs, const ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur_dashboard_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef94c03da2e53bb8c576236bb003fe8a";
  }

  static const char* value(const ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef94c03da2e53bb8ULL;
  static const uint64_t static_value2 = 0xc576236bb003fe8aULL;
};

template<class ContainerAllocator>
struct DataType< ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur_dashboard_msgs/GetRobotModeResponse";
  }

  static const char* value(const ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RobotMode robot_mode\n"
"string answer\n"
"bool success\n"
"\n"
"\n"
"================================================================================\n"
"MSG: ur_dashboard_msgs/RobotMode\n"
"int8 NO_CONTROLLER=-1\n"
"int8 DISCONNECTED=0\n"
"int8 CONFIRM_SAFETY=1\n"
"int8 BOOTING=2\n"
"int8 POWER_OFF=3\n"
"int8 POWER_ON=4\n"
"int8 IDLE=5\n"
"int8 BACKDRIVE=6\n"
"int8 RUNNING=7\n"
"int8 UPDATING_FIRMWARE=8\n"
"\n"
"int8 mode\n"
"\n"
;
  }

  static const char* value(const ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_mode);
      stream.next(m.answer);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRobotModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur_dashboard_msgs::GetRobotModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "robot_mode: ";
    s << std::endl;
    Printer< ::ur_dashboard_msgs::RobotMode_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_mode);
    s << indent << "answer: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.answer);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR_DASHBOARD_MSGS_MESSAGE_GETROBOTMODERESPONSE_H
